### ISSUE TITLE
jsonschema 생성

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/cli#5]
jsonschema를 만들어서 사용자가 자동완성할 수 있게 끔 도와주었으면 좋겠습니다.
참고자료: https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-add-a-json-schema-thats-self-hostedremoteexternal

**Comment by geonmo-nine** [comment]
작업 완료했습니다~!

**Comment by yceffort-naver** [comment]
띠용 어떻게 하셨나용?

**Comment by geonmo-nine** [comment]
https://raw.githubusercontent.com/NaverPayDev/cli/main/packages/commit-helper/src/schema.json
